default_language_version:
  python: python{{ cookiecutter.minimal_python_version }}

default_stages: [ commit, push ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-json
      - id: check-xml
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [ '--branch', 'main', '--branch', 'master' ]
      - id: pretty-format-json
        args: [ '--autofix' ]
      - id: trailing-whitespace
        args: [ '--markdown-linebreak-ext=md' ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [ "--py{{ cookiecutter.minimal_python_version.replace('.', '') }}-plus" ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ '--settings-path', 'pyproject.toml' ]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.2.0
    hooks:
      - id: black
        args: [ '--config', 'pyproject.toml' ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [ '--config-file', 'pyproject.toml']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: [ '-ll','--recursive', "{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}", 'tests' ]
